### ISSUE TITLE
Error import Args from nestipy.ioc

### ISSUE THREAD

**Issue by TianaNanta** [nestipy/nestipy#4]
`File "/home/nanta/Project/Python/nesty/user/user_resolver.py", line 7, in <module>
    from nestipy.ioc import Args
ImportError: cannot import name 'Args' from 'nestipy.ioc'`

When using your example, I get this error when starting the app

**Comment by tsiresymila1** [comment]
We have made a major update. Please update nestipy to the latest version and check the documentation [here](https://nestipy.vercel.app/graphql/quick-start).

**Comment by TianaNanta** [comment]
I just copy your example project to test it and then it gives this error
You should correct also your example in that case
